name: mobile_app
description: "Juno - AI-Powered Financial Assistant Mobile App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  
  web_socket_channel:
  http:
  
  # State management
  provider:
  
  # UI and animations
  animated_text_kit:
  lottie:
  
  # Utilities
  uuid:
  intl:
  url_launcher:
  
  # Firebase Authentication (let Flutter choose compatible versions)
  firebase_core:
  firebase_auth:
  
  # Firestore for chat history storage
  cloud_firestore:
  speech_to_text: ^7.2.0
  permission_handler: ^12.0.1

  google_speech: ^5.0.0
  record: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/credentials/

