name: mobile_app
description: "Juno - AI-Powered Financial Assistant Mobile App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  
  web_socket_channel:
  http:
  
  # State management
  provider:
  
  # UI and animations
  animated_text_kit:
  lottie:
  
  # Utilities
  uuid:
  intl:
  url_launcher:
  
  # Firebase Authentication
  firebase_core:
  firebase_auth:
  
  # Firestore for chat history storage
  cloud_firestore:
  
  # Web-compatible speech recognition (uses browser's Web Speech API)
  speech_to_text: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  # Remove the credentials asset - not needed for web